# Generated by Django 3.0.9 on 2020-08-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_meta',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file_meta',
            name='size',
        ),
        migrations.AddField(
            model_name='file_meta',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
