# Generated by Django 3.0.9 on 2020-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20200805_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_meta',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
