# Generated by Django 3.0.9 on 2020-08-06 03:34

from django.db import migrations, models
import quickstart.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20200805_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_meta',
            name='file',
            field=models.FileField(upload_to='', validators=[quickstart.validators.validate_file_extension]),
        ),
    ]
